// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
    #define LV_ATTRIBUTE_MEM_ALIGN
#endif

// IMAGE DATA: assets/429664019d414bdf80281a16a296bc8a.jpeg~tplv-a9rns2rl98-downsize_watermark_1_5_b.png
const LV_ATTRIBUTE_MEM_ALIGN uint8_t ui_img_1301672413_data[] = { 0 };
lv_img_dsc_t ui_img_1301672413 = {
    .header.always_zero = 0,
    .header.w = 64,
    .header.h = 64,
    .data_size = 0,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .data = NULL
};

