// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
    #define LV_ATTRIBUTE_MEM_ALIGN
#endif

// IMAGE DATA: assets/屏幕截图 2026-06-22 111053.png
const LV_ATTRIBUTE_MEM_ALIGN uint8_t ui_img_1565185032_data[] = { 0 };
lv_img_dsc_t ui_img_1565185032 = {
    .header.always_zero = 0,
    .header.w = 64,
    .header.h = 64,
    .data_size = 0,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .data = NULL
};

