// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREENSETTINGS_H
#define UI_SCREENSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screensettings
extern void ui_Screensettings_screen_init(void);
extern void ui_Screensettings_screen_destroy(void);
extern void ui_Screensettings_screen_relocalize(void);
extern void ui_event_Screensettings(lv_event_t * e);
extern lv_obj_t * ui_Screensettings;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

