// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREENMAIN_H
#define UI_SCREENMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screenmain
extern void ui_Screenmain_screen_init(void);
extern void ui_Screenmain_screen_destroy(void);
extern void ui_Screenmain_screen_relocalize(void);
extern void ui_event_Screenmain(lv_event_t * e);
extern lv_obj_t * ui_Screenmain;
extern lv_obj_t * ui_HEAD;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_ImgButton4;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_ImgButton5;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

