/**
 * ui_Screensettings.c -- System settings page
 *
 * Contains five tabviews:
 *   Gain    -- GPS, Bluetooth, WeChat, ROS Nav, Voice gain sliders
 *   Remote  -- BT linear/angular speed, WeChat speed scale, ROS max speed sliders
 *   PID     -- Speed Kp/Ki/Kd and max output sliders
 *   Mode    -- Car mode selector buttons (GPS/GPS+ROS/Bluetooth/WeChat/ROS Indoor/Voice)
 *   Status  -- Live telemetry display (mode, GPS, IMU yaw, magnetometer,
 *              wheel RPM, init status)
 *
 * All slider values are read from / written to ChassisSettings_t via the
 * chassis_set_gain_param / chassis_set_remote_param / chassis_set_pid_param
 * API.  Mode changes go through chassis_request_mode().
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "app_chassis_board.h"
#include <stdio.h>
#include <stdint.h>

lv_obj_t * ui_Screensettings = NULL;
lv_obj_t * ui_Image1 = NULL;
static lv_timer_t *settings_status_timer = NULL;
static lv_obj_t *settings_status_label = NULL;

typedef struct {
    uint8_t type;
    uint8_t param;
    uint16_t scale;
    lv_obj_t *slider;
    lv_obj_t *label;
} settings_item_t;

#define SETTINGS_ITEM_MAX  16U
#define SETTINGS_TYPE_GAIN   0U
#define SETTINGS_TYPE_REMOTE 1U
#define SETTINGS_TYPE_PID    2U

static settings_item_t settings_items[SETTINGS_ITEM_MAX];
static uint8_t settings_item_count = 0U;

static const char *settings_mode_name(CarMode_t mode)
{
    switch (mode) {
    case CAR_MODE_IDLE:    return "No Power";
    case CAR_MODE_GPS:     return "GPS";
    case CAR_MODE_GPS_ROS: return "GPS+ROS";
    case CAR_MODE_REMOTE:  return "WeChat";
    case CAR_MODE_LINE:    return "ROS Indoor";
    case CAR_MODE_INDOOR:  return "Bluetooth";
    case CAR_MODE_VOICE:   return "Voice";
    default:               return "--";
    }
}

static float settings_item_get(settings_item_t *item)
{
    ChassisSettings_t settings;

    if (item == NULL) return 0.0f;

    chassis_get_settings(&settings);

    if (item->type == SETTINGS_TYPE_GAIN) {
        switch ((ChassisGainParam_t)item->param) {
        case CHASSIS_GAIN_PARAM_GPS:    return settings.gain.gps;
        case CHASSIS_GAIN_PARAM_INDOOR: return settings.gain.indoor;
        case CHASSIS_GAIN_PARAM_REMOTE: return settings.gain.remote;
        case CHASSIS_GAIN_PARAM_LINE:   return settings.gain.line;
        case CHASSIS_GAIN_PARAM_VOICE:  return settings.gain.voice;
        default: break;
        }
    } else if (item->type == SETTINGS_TYPE_REMOTE) {
        switch ((ChassisRemoteParam_t)item->param) {
        case CHASSIS_REMOTE_PARAM_BT_SPEED:        return settings.remote.bt_speed;
        case CHASSIS_REMOTE_PARAM_BT_WZ:           return settings.remote.bt_wz;
        case CHASSIS_REMOTE_PARAM_WECHAT_VX_SCALE: return settings.remote.wechat_vx_scale;
        case CHASSIS_REMOTE_PARAM_ROS_MAX_SPEED:   return settings.remote.ros_max_speed;
        default: break;
        }
    } else if (item->type == SETTINGS_TYPE_PID) {
        switch ((ChassisPidParam_t)item->param) {
        case CHASSIS_PID_PARAM_KP:      return (float)settings.pid_param.kp;
        case CHASSIS_PID_PARAM_KI:      return (float)settings.pid_param.ki;
        case CHASSIS_PID_PARAM_KD:      return (float)settings.pid_param.kd;
        case CHASSIS_PID_PARAM_MAX_OUT: return (float)settings.pid_param.max_out;
        default: break;
        }
    }

    return 0.0f;
}

static void settings_item_set(settings_item_t *item, float value)
{
    if (item == NULL) return;

    if (item->type == SETTINGS_TYPE_GAIN) {
        chassis_set_gain_param((ChassisGainParam_t)item->param, value);
    } else if (item->type == SETTINGS_TYPE_REMOTE) {
        chassis_set_remote_param((ChassisRemoteParam_t)item->param, value);
    } else if (item->type == SETTINGS_TYPE_PID) {
        chassis_set_pid_param((ChassisPidParam_t)item->param, (double)value);
    }
}

static void settings_item_refresh(settings_item_t *item)
{
    char buf[24];
    float value;

    if (item == NULL || item->label == NULL) return;

    value = settings_item_get(item);
    snprintf(buf, sizeof(buf), "%.2f", value);
    lv_label_set_text(item->label, buf);
}

static void settings_slider_cb(lv_event_t *e)
{
    settings_item_t *item = (settings_item_t *)lv_event_get_user_data(e);
    int32_t raw;
    float value;

    if (item == NULL || item->slider == NULL) return;

    raw = lv_slider_get_value(item->slider);
    value = (float)raw / (float)item->scale;
    settings_item_set(item, value);
    settings_item_refresh(item);
}

static lv_obj_t *settings_make_tab(lv_obj_t *tv, const char *name)
{
    lv_obj_t *tab = lv_tabview_add_tab(tv, name);
    ui_apply_gradient_background(tab, 0xF8FAFA, 0xDFF4F5, LV_GRAD_DIR_VER);
    lv_obj_set_style_pad_all(tab, 16, 0);
    lv_obj_set_scroll_dir(tab, LV_DIR_VER);
    return tab;
}

static void settings_add_slider(lv_obj_t *parent, const char *name, uint8_t type,
                                uint8_t param, float min, float max,
                                uint16_t scale)
{
    settings_item_t *item;
    lv_obj_t *row;
    lv_obj_t *title;
    int32_t vmin;
    int32_t vmax;
    int32_t vcur;
    uint32_t row_index;

    if (settings_item_count >= SETTINGS_ITEM_MAX) return;

    item = &settings_items[settings_item_count++];
    item->type = type;
    item->param = param;
    item->scale = scale;

    row_index = lv_obj_get_child_cnt(parent);
    row = lv_obj_create(parent);
    lv_obj_set_size(row, 930, 82);
    lv_obj_set_pos(row, 8, (lv_coord_t)(row_index * 92U));
    lv_obj_set_style_bg_color(row, lv_color_hex(UI_COLOR_CARD), 0);
    lv_obj_set_style_border_color(row, lv_color_hex(UI_COLOR_CYAN_SOFT), 0);
    lv_obj_set_style_border_width(row, 1, 0);
    lv_obj_set_style_radius(row, 8, 0);
    lv_obj_set_style_pad_all(row, 0, 0);
    ui_apply_raised_panel(row);
    lv_obj_clear_flag(row, LV_OBJ_FLAG_SCROLLABLE);

    title = lv_label_create(row);
    lv_label_set_text(title, name);
    lv_obj_set_style_text_color(title, lv_color_hex(UI_COLOR_TEXT), 0);
    lv_obj_set_style_text_font(title, &lv_font_montserrat_14, 0);
    lv_obj_set_pos(title, 16, 12);

    item->slider = lv_slider_create(row);
    lv_obj_set_size(item->slider, 520, 14);
    lv_obj_set_pos(item->slider, 205, 34);
    vmin = (int32_t)(min * (float)scale);
    vmax = (int32_t)(max * (float)scale);
    vcur = (int32_t)(settings_item_get(item) * (float)scale);
    lv_slider_set_range(item->slider, vmin, vmax);
    lv_slider_set_value(item->slider, vcur, LV_ANIM_OFF);
    lv_obj_set_style_bg_color(item->slider, lv_color_hex(UI_COLOR_CYAN_SOFT), LV_PART_MAIN);
    lv_obj_set_style_bg_color(item->slider, lv_color_hex(UI_COLOR_CYAN), LV_PART_INDICATOR);
    lv_obj_set_style_bg_color(item->slider, lv_color_hex(UI_COLOR_BLUE_DARK), LV_PART_KNOB);
    lv_obj_add_event_cb(item->slider, settings_slider_cb, LV_EVENT_VALUE_CHANGED, item);

    item->label = lv_label_create(row);
    lv_obj_set_width(item->label, 90);
    lv_obj_set_pos(item->label, 805, 31);
    lv_obj_set_style_text_color(item->label, lv_color_hex(UI_COLOR_CYAN_DARK), 0);
    lv_obj_set_style_text_align(item->label, LV_TEXT_ALIGN_RIGHT, 0);
    settings_item_refresh(item);
}

static void settings_mode_cb(lv_event_t *e)
{
    int mode = (int)(uintptr_t)lv_event_get_user_data(e);

    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        chassis_request_mode((CarMode_t)mode);
    }
}

static void settings_add_mode_button(lv_obj_t *parent, const char *name, CarMode_t mode,
                                     lv_coord_t x, lv_coord_t y)
{
    lv_obj_t *btn = lv_btn_create(parent);
    lv_obj_t *label;

    lv_obj_set_size(btn, 130, 42);
    lv_obj_set_pos(btn, x, y);
    lv_obj_set_style_bg_color(btn, lv_color_hex(UI_COLOR_BLUE_DARK), 0);
    ui_apply_raised_button(btn);
    lv_obj_add_event_cb(btn, settings_mode_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)mode);

    label = lv_label_create(btn);
    lv_label_set_text(label, name);
    lv_obj_center(label);
}

static void settings_refresh_status(void)
{
    char status[512];
    char init_status[64];
    ChassisTelemetry_t data;
    uint8_t gps_online = 0U;

    if (settings_status_label == NULL) return;

    chassis_get_telemetry(&data);
    chassis_get_status_text(init_status, sizeof(init_status));
    gps_online = (data.gps_last_update_tick != 0U &&
                  (HAL_GetTick() - data.gps_last_update_tick) <= 3000U) ? 1U : 0U;

    snprintf(status, sizeof(status),
             "Mode: %s\n"
             "GPS: %s  Lat %.5f  Lon %.5f  Sat %d\n"
             "Time: %02u:%02u:%02u\n"
             "IMU Yaw: %.1f  Mag: %s\n"
             "Wheel rpm: %.1f %.1f %.1f %.1f\n"
             "Init: %s",
             settings_mode_name(data.mode),
             gps_online ? "ONLINE" : "OFFLINE",
             data.gps_lat,
             data.gps_lon,
             data.gps_sats,
             (unsigned)data.gps_hour,
             (unsigned)data.gps_minute,
             (unsigned)data.gps_second,
             data.ins_yaw,
             data.qmc_calibrating ? "CALIB" : "READY",
             (float)data.motor_speed[0],
             (float)data.motor_speed[1],
             (float)data.motor_speed[2],
             (float)data.motor_speed[3],
             init_status);
    lv_label_set_text(settings_status_label, status);
}

static void settings_status_timer_cb(lv_timer_t *t)
{
    (void)t;
    if (lv_scr_act() == ui_Screensettings) settings_refresh_status();
}
// event functions
void ui_event_Screensettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED || lv_event_get_code(e) == LV_EVENT_LONG_PRESSED || event_code == LV_EVENT_GESTURE) {
        _ui_screen_change(&ui_Screenmain, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 200, &ui_Screenmain_screen_init);
    }
}

// build functions

void ui_Screensettings_screen_init(void)
{
    lv_obj_t *title;
    lv_obj_t *back;
    lv_obj_t *back_label;
    lv_obj_t *tv;
    lv_obj_t *tab_gain;
    lv_obj_t *tab_remote;
    lv_obj_t *tab_mode;
    lv_obj_t *tab_pid;
    lv_obj_t *tab_status;

    ui_Screensettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screensettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_apply_gradient_background(ui_Screensettings, 0xFFFFFF, 0xDFF4F5, LV_GRAD_DIR_VER);

    settings_item_count = 0U;
    ui_Image1 = NULL;

    title = lv_label_create(ui_Screensettings);
    lv_label_set_text(title, "System Settings");
    lv_obj_set_style_text_color(title, lv_color_hex(UI_COLOR_BLUE_DARK), 0);
    lv_obj_set_style_text_font(title, &lv_font_montserrat_14, 0);
    lv_obj_align(title, LV_ALIGN_TOP_MID, 0, 8);

    back = lv_btn_create(ui_Screensettings);
    lv_obj_set_size(back, 78, 34);
    lv_obj_align(back, LV_ALIGN_TOP_RIGHT, -12, 8);
    lv_obj_set_style_bg_color(back, lv_color_hex(UI_COLOR_BLUE_DARK), 0);
    ui_apply_raised_button(back);
    lv_obj_add_event_cb(back, ui_event_Screensettings, LV_EVENT_CLICKED, NULL);
    back_label = lv_label_create(back);
    lv_label_set_text(back_label, "Back");
    lv_obj_center(back_label);

    tv = lv_tabview_create(ui_Screensettings, LV_DIR_TOP, 34);
    lv_obj_set_size(tv, 980, 540);
    lv_obj_align(tv, LV_ALIGN_BOTTOM_MID, 0, -8);
    ui_apply_raised_panel(tv);

    tab_gain = settings_make_tab(tv, "Gain");
    tab_remote = settings_make_tab(tv, "Remote");
    tab_mode = settings_make_tab(tv, "Mode");
    tab_pid = settings_make_tab(tv, "PID");
    tab_status = settings_make_tab(tv, "Status");

    settings_add_slider(tab_gain, "GPS Nav Gain", SETTINGS_TYPE_GAIN, CHASSIS_GAIN_PARAM_GPS, 0.0f, 2.0f, 100U);
    settings_add_slider(tab_gain, "Bluetooth Gain", SETTINGS_TYPE_GAIN, CHASSIS_GAIN_PARAM_INDOOR, 0.0f, 2.0f, 100U);
    settings_add_slider(tab_gain, "WeChat Gain", SETTINGS_TYPE_GAIN, CHASSIS_GAIN_PARAM_REMOTE, 0.0f, 2.0f, 100U);
    settings_add_slider(tab_gain, "ROS Nav Gain", SETTINGS_TYPE_GAIN, CHASSIS_GAIN_PARAM_LINE, 0.0f, 2.0f, 100U);
    settings_add_slider(tab_gain, "Voice Gain", SETTINGS_TYPE_GAIN, CHASSIS_GAIN_PARAM_VOICE, 0.0f, 2.0f, 100U);

    settings_add_slider(tab_remote, "BT Linear Speed", SETTINGS_TYPE_REMOTE, CHASSIS_REMOTE_PARAM_BT_SPEED, 0.0f, 200.0f, 1U);
    settings_add_slider(tab_remote, "BT Angular Speed", SETTINGS_TYPE_REMOTE, CHASSIS_REMOTE_PARAM_BT_WZ, 0.0f, 100.0f, 1U);
    settings_add_slider(tab_remote, "WeChat Speed Scale", SETTINGS_TYPE_REMOTE, CHASSIS_REMOTE_PARAM_WECHAT_VX_SCALE, 0.0f, 200.0f, 1U);
    settings_add_slider(tab_remote, "ROS Max Speed", SETTINGS_TYPE_REMOTE, CHASSIS_REMOTE_PARAM_ROS_MAX_SPEED, 0.0f, 150.0f, 1U);

    settings_add_slider(tab_pid, "Speed KP", SETTINGS_TYPE_PID, CHASSIS_PID_PARAM_KP, 0.0f, 3.0f, 100U);
    settings_add_slider(tab_pid, "Speed KI", SETTINGS_TYPE_PID, CHASSIS_PID_PARAM_KI, 0.0f, 1.0f, 100U);
    settings_add_slider(tab_pid, "Speed KD", SETTINGS_TYPE_PID, CHASSIS_PID_PARAM_KD, 0.0f, 1.0f, 100U);
    settings_add_slider(tab_pid, "PID Max Out", SETTINGS_TYPE_PID, CHASSIS_PID_PARAM_MAX_OUT, 0.0f, 300.0f, 1U);

    settings_add_mode_button(tab_mode, "GPS", CAR_MODE_GPS, 40, 30);
    settings_add_mode_button(tab_mode, "GPS+ROS", CAR_MODE_GPS_ROS, 200, 30);
    settings_add_mode_button(tab_mode, "Bluetooth", CAR_MODE_INDOOR, 360, 30);
    settings_add_mode_button(tab_mode, "WeChat", CAR_MODE_REMOTE, 520, 30);
    settings_add_mode_button(tab_mode, "ROS Indoor", CAR_MODE_LINE, 680, 30);
    settings_add_mode_button(tab_mode, "Voice", CAR_MODE_VOICE, 40, 92);

    settings_status_label = lv_label_create(tab_status);
    lv_obj_set_width(settings_status_label, 880);
    lv_obj_set_style_text_color(settings_status_label, lv_color_hex(UI_COLOR_TEXT), 0);
    lv_obj_set_style_text_font(settings_status_label, &lv_font_montserrat_14, 0);
    lv_obj_align(settings_status_label, LV_ALIGN_TOP_LEFT, 18, 20);
    settings_refresh_status();

    lv_obj_add_event_cb(ui_Screensettings, touch_reset_idle, LV_EVENT_PRESSED, NULL);

    if (settings_status_timer == NULL) {
        settings_status_timer = lv_timer_create(settings_status_timer_cb, 500, NULL);
    }
}

void ui_Screensettings_screen_destroy(void)
{
    if (settings_status_timer) {
        lv_timer_del(settings_status_timer);
        settings_status_timer = NULL;
    }

    if(ui_Screensettings) lv_obj_del(ui_Screensettings);

    // NULL screen variables
    ui_Screensettings = NULL;
    ui_Image1 = NULL;
    settings_status_label = NULL;
    settings_item_count = 0U;

}

void ui_Screensettings_screen_relocalize(void)
{
    // label widgets on screen

}
