// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screensettings = NULL;
lv_obj_t * ui_Image1 = NULL;
// event funtions
void ui_event_Screensettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED || lv_event_get_code(e) == LV_EVENT_LONG_PRESSED || event_code == LV_EVENT_GESTURE) {
        _ui_screen_change(&ui_Screenmain, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 200, &ui_Screenmain_screen_init);
    }
}

// build funtions

void ui_Screensettings_screen_init(void)
{
    ui_Screensettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screensettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screensettings, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screensettings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_Image1 = lv_img_create(ui_Screensettings);
    lv_img_set_src(ui_Image1, &ui_img_1943878613);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1024
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 600
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screensettings, ui_event_Screensettings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screensettings, touch_reset_idle, LV_EVENT_PRESSED, NULL);

}

void ui_Screensettings_screen_destroy(void)
{
    if(ui_Screensettings) lv_obj_del(ui_Screensettings);

    // NULL screen variables
    ui_Screensettings = NULL;
    ui_Image1 = NULL;

}

void ui_Screensettings_screen_relocalize(void)
{
    // label widgets on screen

}
