// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screenmain_screen_init();
    ui_Screensettings_screen_init();
	    ui_FileManager_screen_init();
	    ui_DataDisplay_screen_init();
	    ui_DataDetail_screen_init();
	    ui_Login_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Login);
}

void ui_destroy(void)
{
    ui_Screenmain_screen_destroy();
    ui_Screensettings_screen_destroy();
	    ui_FileManager_screen_destroy();
	    ui_DataDisplay_screen_destroy();
	    ui_DataDetail_screen_destroy();
	    ui_Login_screen_destroy();
}

void ui_relocalize(void)
{
    ui_Screenmain_screen_relocalize();
    ui_Screensettings_screen_relocalize();
}
